
# **Neural Networks implemented in Python's Tensor flow**

## **Part 1, fundementals:**

### **Section 1, making tensors:**

    First we import Tensorflow & numpy so we don't have to implement all of this from scratch

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import tensorflow as tf

In [4]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\samia\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


    Now lets create our first tensors
    Each tensor has a datatype & a shape attribute
    Usually they hold numbers, but lets create a couple of datatypes

In [5]:
string = tf.Variable("this string will be added to the tensor", tf.string)
number = tf.Variable(1231234213, tf.int16)
float = tf.Variable(3.14159, tf.float64) 

In [7]:
print(string); print(number); print(float)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this string will be added to the tensor'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1231234213>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14159>


    And to create tensors of a rank of 1, 2, or 3, we do as follows
    Rank and degree both being terms for the number of dimensions

In [40]:
rank1 = tf.Variable(["rank1"], tf.string)

rank2 = tf.Variable(
    [["rank2 1a", "2a"],["rank2 1b", "2b"]
], tf.string)

rank3 = tf.Variable([
    [["rank3 1a", "1b"], ["1c", "1d"]],
    [["rank3 2a", "2b"], ["2c", "2d"]]
], tf.string)


rank4 = tf.Variable([
    [
        [["rank4 1a", "1b"], ["1c", "1d"]],
        [["rank4 2a", "2b"], ["2c", "2d"]]],[
        [["rank4 3a", "3b"], ["3c", "3d"]],
        [["rank4 4a", "4b"], ["4c", "4d"]]
    ]
], tf.string)

In [41]:
all_ranks = [rank1, rank2, rank3, rank4]
for i, rank in enumerate(all_ranks):
    tf.print(f"Rank {i+1}:", rank)
    # tf.print(f"Rank {i+1} shape:", rank.shape)
    print("")

Rank 1: ["rank1"]

Rank 2: [["rank2 1a" "2a"]
 ["rank2 1b" "2b"]]

Rank 3: [[["rank3 1a" "1b"]
  ["1c" "1d"]]

 [["rank3 2a" "2b"]
  ["2c" "2d"]]]

Rank 4: [[[["rank4 1a" "1b"]
   ["1c" "1d"]]

  [["rank4 2a" "2b"]
   ["2c" "2d"]]]


 [[["rank4 3a" "3b"]
   ["3c" "3d"]]

  [["rank4 4a" "4b"]
   ["4c" "4d"]]]]



In [42]:
all_ranks = [rank1, rank2, rank3, rank4]
for i, rank in enumerate(all_ranks):
    tf.print(f"Rank {i+1} shape:", rank.shape)

Rank 1 shape: TensorShape([1])
Rank 2 shape: TensorShape([2, 2])
Rank 3 shape: TensorShape([2, 2, 2])
Rank 4 shape: TensorShape([2, 2, 2, 2])


    Of course these don't need to be square

In [43]:
rank1a = tf.Variable(["rank1", "rank1", "rank1", "rank1", "rank1", "rank1", "rank1", "rank1"], tf.string);  tf.print(rank1a);   tf.print(rank1a.shape)

["rank1" "rank1" "rank1" ... "rank1" "rank1" "rank1"]
TensorShape([8])


In [44]:
rank2a = tf.Variable(
    [["rank2 1a", "2a", "3a", "4a", "5a"],["rank2 1b", "2b", "3b", "4b", "5b"]
], tf.string);  tf.print(rank2a);   tf.print(rank2a.shape)

[["rank2 1a" "2a" "3a" "4a" "5a"]
 ["rank2 1b" "2b" "3b" "4b" "5b"]]
TensorShape([2, 5])


    But they do need to be rectangular

In [45]:
try:
    rank3a = tf.Variable(
        [["rank2 1a", "2a", "3a", "4a", "5a"],["rank2 1b", "2b"]
    ], tf.string);  tf.print(rank3a)
except ValueError as e:
    print(f"Error: {e}")

Error: Can't convert non-rectangular Python sequence to Tensor.


    But once you follow the above rules you can now build a large tensor & process it efficiently

In [49]:

rank5 = tf.Variable(
    [[[[["rank5"] * 5 for _ in range(5)] for _ in range(5)] for _ in range(5)] for _ in range(5)],
    tf.string
)

# tf.print("Stuff in rank5:", (rank5))
tf.print("Shape of rank5:", tf.shape(rank5))


Shape of rank5: [5 5 5 5 5]


### **Some useful tools:**

    We've already used tf.print to make the output look better
    And we can also use tf.ones to make a tensor of ones

In [54]:
tensor1 = tf.ones([2, 3, 5])
tf.print(tensor1.shape); tf.print(tensor1)

TensorShape([2, 3, 5])
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


### **Section 2, changing the shape of tensors:**

    Now lets see how we can reshape this tensor

    Here we reshape to a specific thing

In [57]:
tensorReshaped = tf.reshape(tensor1, [5, 2, 3])
tf.print(tensorReshaped.shape); tf.print(tensorReshaped)

TensorShape([5, 2, 3])
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


    But we could also ask it to reshape 1 dimension & calculate the rest itself (with a -1)

In [58]:
tensorReshaped = tf.reshape(tensor1, [5, -1])
tf.print(tensorReshaped.shape); tf.print(tensorReshaped)

TensorShape([5, 6])
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


### **Lets make something cool now:**

    In addition to tf.print & tf.ones:
    We can tf.zeros for a 0 tensor

In [69]:
tensor0 = tf.zeros([1, 3, 6])
tf.print(tensor0.shape); tf.print(tensor0)

TensorShape([1, 3, 6])
[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]]


    or tf.eye for the identity matrix

In [80]:
tensorI = tf.eye(5)
tf.print(tensorI.shape); tf.print(tensorI)

TensorShape([5, 5])
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
